[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC005'
url = 'https://atcoder.jp/contests/ABC005?lang=ja'

[tasks]
[tasks.a]
id = 'abc005_1'
path = '/home/kshino/workspace/compe_prog_new/ABC005/a/main.py'

[tasks.b]
id = 'abc005_2'
path = '/home/kshino/workspace/compe_prog_new/ABC005/b/main.py'

[tasks.c]
id = 'abc005_3'
path = '/home/kshino/workspace/compe_prog_new/ABC005/c/main.py'

[tasks.d]
id = 'abc005_4'
path = '/home/kshino/workspace/compe_prog_new/ABC005/d/main.py'


