[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC023'
url = 'https://atcoder.jp/contests/ABC023?lang=ja'

[tasks]
[tasks.a]
id = 'abc023_a'
path = '/home/kshino/workspace/compe_prog_new/ABC023/a/main.py'

[tasks.b]
id = 'abc023_b'
path = '/home/kshino/workspace/compe_prog_new/ABC023/b/main.py'

[tasks.c]
id = 'abc023_c'
path = '/home/kshino/workspace/compe_prog_new/ABC023/c/main.py'

[tasks.d]
id = 'abc023_d'
path = '/home/kshino/workspace/compe_prog_new/ABC023/d/main.py'


