[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc346'
url = 'https://atcoder.jp/contests/abc346?lang=ja'

[tasks]
[tasks.a]
id = 'abc346_a'
path = '/home/kshino/workspace/compe_prog_new/abc346/a/main.py'

[tasks.b]
id = 'abc346_b'
path = '/home/kshino/workspace/compe_prog_new/abc346/b/main.py'

[tasks.c]
id = 'abc346_c'
path = '/home/kshino/workspace/compe_prog_new/abc346/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc346/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc346/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc346/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc346/g/main.py'
