[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC084'
url = 'https://atcoder.jp/contests/ABC084?lang=ja'

[tasks]
[tasks.a]
id = 'abc084_a'
path = '/home/kshino/workspace/compe_prog_new/ABC084/a/main.py'

[tasks.b]
id = 'abc084_b'
path = '/home/kshino/workspace/compe_prog_new/ABC084/b/main.py'

[tasks.c]
id = 'abc084_c'
path = '/home/kshino/workspace/compe_prog_new/ABC084/c/main.py'

[tasks.d]
id = 'abc084_d'
path = '/home/kshino/workspace/compe_prog_new/ABC084/d/main.py'


