[config]
buildcmd = ''
filename = 'main.py'
lang = '4006'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC265'
url = 'https://atcoder.jp/contests/ABC265?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC265/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC265/b/main.py'

[tasks.c]
id = 'abc265_c'
path = '/home/kshino/workspace/compe_prog_new/ABC265/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC265/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC265/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC265/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC265/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC265/g/main.py'


