[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc234'
url = 'https://atcoder.jp/contests/abc234?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/b/main.py'

[tasks.c]
id = 'abc234_c'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231108day/ABC234/g/main.py'
