[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abl'
url = 'https://atcoder.jp/contests/abl?lang=ja'

[tasks]
[tasks.a]
id = 'abl_a'
path = '/home/kshino/workspace/compe_prog_new/other/abl/a/main.py'

[tasks.b]
id = 'abl_b'
path = '/home/kshino/workspace/compe_prog_new/other/abl/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/abl/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/abl/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/abl/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/abl/f/main.py'


