[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC201'
url = 'https://atcoder.jp/contests/ABC201?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC201/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC201/b/main.py'

[tasks.c]
id = 'abc201_c'
path = '/home/kshino/workspace/compe_prog_new/ABC201/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC201/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC201/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC201/f/main.py'


