[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc325'
url = 'https://atcoder.jp/contests/abc325?lang=ja'

[tasks]
[tasks.a]
id = 'abc325_a'
path = '/home/kshino/workspace/compe_prog_new/abc325/a/main.py'

[tasks.b]
id = 'abc325_b'
path = '/home/kshino/workspace/compe_prog_new/abc325/b/main.py'

[tasks.c]
id = 'abc325_c'
path = '/home/kshino/workspace/compe_prog_new/abc325/c/main.py'

[tasks.d]
id = 'abc325_d'
path = '/home/kshino/workspace/compe_prog_new/abc325/d/main.py'

[tasks.e]
id = 'abc325_e'
path = '/home/kshino/workspace/compe_prog_new/abc325/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc325/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc325/g/main.py'
