[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc354'
url = 'https://atcoder.jp/contests/abc354?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc354/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc354/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc354/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc354/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc354/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc354/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc354/g/main.py'
