[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC310'
url = 'https://atcoder.jp/contests/ABC310?lang=ja'

[tasks]
[tasks.a]
id = 'abc310_a'
path = '/home/kshino/workspace/compe_prog_new/ABC310/a/main.py'

[tasks.b]
id = 'abc310_b'
path = '/home/kshino/workspace/compe_prog_new/ABC310/b/main.py'

[tasks.c]
id = 'abc310_c'
path = '/home/kshino/workspace/compe_prog_new/ABC310/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC310/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC310/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC310/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC310/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC310/g/main.py'


