[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'jsc2021'
url = 'https://atcoder.jp/contests/jsc2021?lang=ja'

[tasks]
[tasks.a]
id = 'jsc2021_a'
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/a/main.py'

[tasks.b]
id = 'jsc2021_b'
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/b/main.py'

[tasks.c]
id = 'jsc2021_c'
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/g/main.py'

[tasks.h]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/jsc2021/h/main.py'


