[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC135'
url = 'https://atcoder.jp/contests/ABC135?lang=ja'

[tasks]
[tasks.a]
id = 'abc135_a'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230523day/ABC135/a/main.py'

[tasks.b]
id = 'abc135_b'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230523day/ABC135/b/main.py'

[tasks.c]
id = 'abc135_c'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230523day/ABC135/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230523day/ABC135/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230523day/ABC135/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230523day/ABC135/f/main.py'


