[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc353'
url = 'https://atcoder.jp/contests/abc353?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc353/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc353/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc353/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc353/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc353/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc353/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc353/g/main.py'
