[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ARC151'
url = 'https://atcoder.jp/contests/ARC151?lang=ja'

[tasks]
[tasks.a]
id = 'arc151_a'
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC151/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC151/b/main.py'

[tasks.c]
id = 'arc151_c'
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC151/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC151/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC151/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC151/f/main.py'


