[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'arc121'
url = 'https://atcoder.jp/contests/arc121?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC121/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC121/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC121/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC121/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC121/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC121/f/main.py'
