[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC063'
url = 'https://atcoder.jp/contests/ABC063?lang=ja'

[tasks]
[tasks.a]
id = 'abc063_a'
path = '/home/kshino/workspace/compe_prog_new/ABC063/a/main.py'

[tasks.b]
id = 'abc063_b'
path = '/home/kshino/workspace/compe_prog_new/ABC063/b/main.py'

[tasks.c]
id = 'arc075_a'
path = '/home/kshino/workspace/compe_prog_new/ABC063/c/main.py'

[tasks.d]
id = 'arc075_b'
path = '/home/kshino/workspace/compe_prog_new/ABC063/d/main.py'


