[config]
buildcmd = ''
filename = 'main.py'
lang = '4006'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC270'
url = 'https://atcoder.jp/contests/ABC270?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC270/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC270/b/main.py'

[tasks.c]
id = 'abc270_c'
path = '/home/kshino/workspace/compe_prog_new/ABC270/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC270/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC270/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC270/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC270/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC270/g/main.py'


