[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc320'
url = 'https://atcoder.jp/contests/abc320?lang=ja'

[tasks]
[tasks.a]
id = 'abc320_a'
path = '/home/kshino/workspace/compe_prog_new/abc320/a/main.py'

[tasks.b]
id = 'abc320_b'
path = '/home/kshino/workspace/compe_prog_new/abc320/b/main.py'

[tasks.c]
id = 'abc320_c'
path = '/home/kshino/workspace/compe_prog_new/abc320/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc320/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc320/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc320/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc320/g/main.py'
