[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC307'
url = 'https://atcoder.jp/contests/ABC307?lang=ja'

[tasks]
[tasks.a]
id = 'abc307_a'
path = '/home/kshino/workspace/compe_prog_new/ABC307/a/main.py'

[tasks.b]
id = 'abc307_b'
path = '/home/kshino/workspace/compe_prog_new/ABC307/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC307/c/main.py'

[tasks.d]
id = 'abc307_d'
path = '/home/kshino/workspace/compe_prog_new/ABC307/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC307/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC307/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC307/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC307/g/main.py'


