[config]
buildcmd = ''
filename = 'main.py'
lang = '4006'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC289'
url = 'https://atcoder.jp/contests/ABC289?lang=ja'

[tasks]
[tasks.a]
id = 'abc289_a'
path = '/home/kshino/workspace/compe_prog_new/ABC289/a/main.py'

[tasks.b]
id = 'abc289_b'
path = '/home/kshino/workspace/compe_prog_new/ABC289/b/main.py'

[tasks.c]
id = 'abc289_c'
path = '/home/kshino/workspace/compe_prog_new/ABC289/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC289/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC289/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC289/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC289/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC289/g/main.py'


