[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC067'
url = 'https://atcoder.jp/contests/ABC067?lang=ja'

[tasks]
[tasks.a]
id = 'abc067_a'
path = '/home/kshino/workspace/compe_prog_new/ABC067/a/main.py'

[tasks.b]
id = 'abc067_b'
path = '/home/kshino/workspace/compe_prog_new/ABC067/b/main.py'

[tasks.c]
id = 'arc078_a'
path = '/home/kshino/workspace/compe_prog_new/ABC067/c/main.py'

[tasks.d]
id = 'arc078_b'
path = '/home/kshino/workspace/compe_prog_new/ABC067/d/main.py'


