[config]
buildcmd = ''
filename = 'main.py'
lang = '4006'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC213'
url = 'https://atcoder.jp/contests/ABC213?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC213/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC213/b/main.py'

[tasks.c]
id = 'abc213_c'
path = '/home/kshino/workspace/compe_prog_new/ABC213/c/main.py'

[tasks.d]
id = 'abc213_d'
path = '/home/kshino/workspace/compe_prog_new/ABC213/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC213/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC213/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC213/g/main.py'

[tasks.h]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC213/h/main.py'


