[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC149'
url = 'https://atcoder.jp/contests/ABC149?lang=ja'

[tasks]
[tasks.a]
id = 'abc149_a'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230522/ABC149/a/main.py'

[tasks.b]
id = 'abc149_b'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230522/ABC149/b/main.py'

[tasks.c]
id = 'abc149_c'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230522/ABC149/c/main.py'

[tasks.d]
id = 'abc149_d'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230522/ABC149/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230522/ABC149/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230522/ABC149/f/main.py'


