[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc348'
url = 'https://atcoder.jp/contests/abc348?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc348/a/main.py'

[tasks.b]
id = 'abc348_b'
path = '/home/kshino/workspace/compe_prog_new/abc348/b/main.py'

[tasks.c]
id = 'abc348_c'
path = '/home/kshino/workspace/compe_prog_new/abc348/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc348/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc348/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc348/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc348/g/main.py'
