[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc278'
url = 'https://atcoder.jp/contests/abc278?lang=ja'

[tasks]
[tasks.a]
id = 'abc278_a'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/a/main.py'

[tasks.b]
id = 'abc278_b'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/b/main.py'

[tasks.c]
id = 'abc278_c'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231016night/ABC278/g/main.py'
