[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC312'
url = 'https://atcoder.jp/contests/ABC312?lang=ja'

[tasks]
[tasks.a]
id = 'abc312_a'
path = '/home/kshino/workspace/compe_prog_new/ABC312/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC312/b/main.py'

[tasks.c]
id = 'abc312_c'
path = '/home/kshino/workspace/compe_prog_new/ABC312/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC312/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC312/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC312/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC312/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC312/g/main.py'


