[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC040'
url = 'https://atcoder.jp/contests/ABC040?lang=ja'

[tasks]
[tasks.a]
id = 'abc040_a'
path = '/home/kshino/workspace/compe_prog_new/ABC040/a/main.py'

[tasks.b]
id = 'abc040_b'
path = '/home/kshino/workspace/compe_prog_new/ABC040/b/main.py'

[tasks.c]
id = 'abc040_c'
path = '/home/kshino/workspace/compe_prog_new/ABC040/c/main.py'

[tasks.d]
id = 'abc040_d'
path = '/home/kshino/workspace/compe_prog_new/ABC040/d/main.py'


