[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC069'
url = 'https://atcoder.jp/contests/ABC069?lang=ja'

[tasks]
[tasks.a]
id = 'abc069_a'
path = '/home/kshino/workspace/compe_prog_new/ABC069/a/main.py'

[tasks.b]
id = 'abc069_b'
path = '/home/kshino/workspace/compe_prog_new/ABC069/b/main.py'

[tasks.c]
id = 'arc080_a'
path = '/home/kshino/workspace/compe_prog_new/ABC069/c/main.py'

[tasks.d]
id = 'arc080_b'
path = '/home/kshino/workspace/compe_prog_new/ABC069/d/main.py'


