[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc334'
url = 'https://atcoder.jp/contests/abc334?lang=ja'

[tasks]
[tasks.a]
id = 'abc334_a'
path = '/home/kshino/workspace/compe_prog_new/abc334/a/main.py'

[tasks.b]
id = 'abc334_b'
path = '/home/kshino/workspace/compe_prog_new/abc334/b/main.py'

[tasks.c]
id = 'abc334_c'
path = '/home/kshino/workspace/compe_prog_new/abc334/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc334/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc334/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc334/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc334/g/main.py'
