[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC036'
url = 'https://atcoder.jp/contests/ABC036?lang=ja'

[tasks]
[tasks.a]
id = 'abc036_a'
path = '/home/kshino/workspace/compe_prog_new/ABC036/a/main.py'

[tasks.b]
id = 'abc036_b'
path = '/home/kshino/workspace/compe_prog_new/ABC036/b/main.py'

[tasks.c]
id = 'abc036_c'
path = '/home/kshino/workspace/compe_prog_new/ABC036/c/main.py'

[tasks.d]
id = 'abc036_d'
path = '/home/kshino/workspace/compe_prog_new/ABC036/d/main.py'


