[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc315'
url = 'https://atcoder.jp/contests/abc315?lang=ja'

[tasks]
[tasks.a]
id = 'abc315_a'
path = '/home/kshino/workspace/compe_prog_new/abc315/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc315/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc315/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc315/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc315/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc315/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc315/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc315/g/main.py'
