[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc321'
url = 'https://atcoder.jp/contests/abc321?lang=ja'

[tasks]
[tasks.a]
id = 'abc321_a'
path = '/home/kshino/workspace/compe_prog_new/abc321/a/main.py'

[tasks.b]
id = 'abc321_b'
path = '/home/kshino/workspace/compe_prog_new/abc321/b/main.py'

[tasks.c]
id = 'abc321_c'
path = '/home/kshino/workspace/compe_prog_new/abc321/c/main.py'

[tasks.d]
id = 'abc321_d'
path = '/home/kshino/workspace/compe_prog_new/abc321/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc321/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc321/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc321/g/main.py'
