[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC030'
url = 'https://atcoder.jp/contests/ABC030?lang=ja'

[tasks]
[tasks.a]
id = 'abc030_a'
path = '/home/kshino/workspace/compe_prog_new/ABC030/a/main.py'

[tasks.b]
id = 'abc030_b'
path = '/home/kshino/workspace/compe_prog_new/ABC030/b/main.py'

[tasks.c]
id = 'abc030_c'
path = '/home/kshino/workspace/compe_prog_new/ABC030/c/main.py'

[tasks.d]
id = 'abc030_d'
path = '/home/kshino/workspace/compe_prog_new/ABC030/d/main.py'


