[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc328'
url = 'https://atcoder.jp/contests/abc328?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc328/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc328/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc328/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc328/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc328/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc328/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc328/g/main.py'
