[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc330'
url = 'https://atcoder.jp/contests/abc330?lang=ja'

[tasks]
[tasks.a]
id = 'abc330_a'
path = '/home/kshino/workspace/compe_prog_new/abc330/a/main.py'

[tasks.b]
id = 'abc330_b'
path = '/home/kshino/workspace/compe_prog_new/abc330/b/main.py'

[tasks.c]
id = 'abc330_c'
path = '/home/kshino/workspace/compe_prog_new/abc330/c/main.py'

[tasks.d]
id = 'abc330_d'
path = '/home/kshino/workspace/compe_prog_new/abc330/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc330/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc330/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc330/g/main.py'
