[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC035'
url = 'https://atcoder.jp/contests/ABC035?lang=ja'

[tasks]
[tasks.a]
id = 'abc035_a'
path = '/home/kshino/workspace/compe_prog_new/ABC035/a/main.py'

[tasks.b]
id = 'abc035_b'
path = '/home/kshino/workspace/compe_prog_new/ABC035/b/main.py'

[tasks.c]
id = 'abc035_c'
path = '/home/kshino/workspace/compe_prog_new/ABC035/c/main.py'

[tasks.d]
id = 'abc035_d'
path = '/home/kshino/workspace/compe_prog_new/ABC035/d/main.py'


