[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc351'
url = 'https://atcoder.jp/contests/abc351?lang=ja'

[tasks]
[tasks.a]
id = 'abc351_a'
path = '/home/kshino/workspace/compe_prog_new/abc351/a/main.py'

[tasks.b]
id = 'abc351_b'
path = '/home/kshino/workspace/compe_prog_new/abc351/b/main.py'

[tasks.c]
id = 'abc351_c'
path = '/home/kshino/workspace/compe_prog_new/abc351/c/main.py'

[tasks.d]
id = 'abc351_d'
path = '/home/kshino/workspace/compe_prog_new/abc351/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc351/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc351/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc351/g/main.py'
