[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'arc126'
url = 'https://atcoder.jp/contests/arc126?lang=ja'

[tasks]
[tasks.a]
id = 'arc126_a'
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC126/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC126/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC126/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC126/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC126/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC126/f/main.py'
