[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC094'
url = 'https://atcoder.jp/contests/ABC094?lang=ja'

[tasks]
[tasks.a]
id = 'abc094_a'
path = '/home/kshino/workspace/compe_prog_new/ABC094/a/main.py'

[tasks.b]
id = 'abc094_b'
path = '/home/kshino/workspace/compe_prog_new/ABC094/b/main.py'

[tasks.c]
id = 'arc095_a'
path = '/home/kshino/workspace/compe_prog_new/ABC094/c/main.py'

[tasks.d]
id = 'arc095_b'
path = '/home/kshino/workspace/compe_prog_new/ABC094/d/main.py'


