[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC066'
url = 'https://atcoder.jp/contests/ABC066?lang=ja'

[tasks]
[tasks.a]
id = 'abc066_a'
path = '/home/kshino/workspace/compe_prog_new/ABC066/a/main.py'

[tasks.b]
id = 'abc066_b'
path = '/home/kshino/workspace/compe_prog_new/ABC066/b/main.py'

[tasks.c]
id = 'arc077_a'
path = '/home/kshino/workspace/compe_prog_new/ABC066/c/main.py'

[tasks.d]
id = 'arc077_b'
path = '/home/kshino/workspace/compe_prog_new/ABC066/d/main.py'


