[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc143'
url = 'https://atcoder.jp/contests/abc143?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231030day/ABC143/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231030day/ABC143/b/main.py'

[tasks.c]
id = 'abc143_c'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231030day/ABC143/c/main.py'

[tasks.d]
id = 'abc143_d'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231030day/ABC143/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231030day/ABC143/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231030day/ABC143/f/main.py'
