[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc209'
url = 'https://atcoder.jp/contests/abc209?lang=ja'

[tasks]
[tasks.a]
id = 'abc209_a'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231011day/ABC209/a/main.py'

[tasks.b]
id = 'abc209_b'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231011day/ABC209/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231011day/ABC209/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231011day/ABC209/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231011day/ABC209/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20231011day/ABC209/f/main.py'
