[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC120'
url = 'https://atcoder.jp/contests/ABC120?lang=ja'

[tasks]
[tasks.a]
id = 'abc120_a'
path = '/home/kshino/workspace/compe_prog_new/ABC120/a/main.py'

[tasks.b]
id = 'abc120_b'
path = '/home/kshino/workspace/compe_prog_new/ABC120/b/main.py'

[tasks.c]
id = 'abc120_c'
path = '/home/kshino/workspace/compe_prog_new/ABC120/c/main.py'

[tasks.d]
id = 'abc120_d'
path = '/home/kshino/workspace/compe_prog_new/ABC120/d/main.py'


