[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC123'
url = 'https://atcoder.jp/contests/ABC123?lang=ja'

[tasks]
[tasks.a]
id = 'abc123_a'
path = '/home/kshino/workspace/compe_prog_new/ABC123/a/main.py'

[tasks.b]
id = 'abc123_b'
path = '/home/kshino/workspace/compe_prog_new/ABC123/b/main.py'

[tasks.c]
id = 'abc123_c'
path = '/home/kshino/workspace/compe_prog_new/ABC123/c/main.py'

[tasks.d]
id = 'abc123_d'
path = '/home/kshino/workspace/compe_prog_new/ABC123/d/main.py'


