[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC064'
url = 'https://atcoder.jp/contests/ABC064?lang=ja'

[tasks]
[tasks.a]
id = 'abc064_a'
path = '/home/kshino/workspace/compe_prog_new/ABC064/a/main.py'

[tasks.b]
id = 'abc064_b'
path = '/home/kshino/workspace/compe_prog_new/ABC064/b/main.py'

[tasks.c]
id = 'abc064_c'
path = '/home/kshino/workspace/compe_prog_new/ABC064/c/main.py'

[tasks.d]
id = 'abc064_d'
path = '/home/kshino/workspace/compe_prog_new/ABC064/d/main.py'


