[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ARC134'
url = 'https://atcoder.jp/contests/ARC134?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC134/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC134/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC134/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC134/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC134/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC134/f/main.py'


