[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC207'
url = 'https://atcoder.jp/contests/ABC207?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC207/a/main.py'

[tasks.b]
id = 'abc207_b'
path = '/home/kshino/workspace/compe_prog_new/ABC207/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC207/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC207/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC207/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC207/f/main.py'


