[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC004'
url = 'https://atcoder.jp/contests/ABC004?lang=ja'

[tasks]
[tasks.a]
id = 'abc004_1'
path = '/home/kshino/workspace/compe_prog_new/ABC004/a/main.py'

[tasks.b]
id = 'abc004_2'
path = '/home/kshino/workspace/compe_prog_new/ABC004/b/main.py'

[tasks.c]
id = 'abc004_3'
path = '/home/kshino/workspace/compe_prog_new/ABC004/c/main.py'

[tasks.d]
id = 'abc004_4'
path = '/home/kshino/workspace/compe_prog_new/ABC004/d/main.py'


