[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC029'
url = 'https://atcoder.jp/contests/ABC029?lang=ja'

[tasks]
[tasks.a]
id = 'abc029_a'
path = '/home/kshino/workspace/compe_prog_new/ABC010/c/ABC029/a/main.py'

[tasks.b]
id = 'abc029_b'
path = '/home/kshino/workspace/compe_prog_new/ABC010/c/ABC029/b/main.py'

[tasks.c]
id = 'abc029_c'
path = '/home/kshino/workspace/compe_prog_new/ABC010/c/ABC029/c/main.py'

[tasks.d]
id = 'abc029_d'
path = '/home/kshino/workspace/compe_prog_new/ABC010/c/ABC029/d/main.py'


