[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC056'
url = 'https://atcoder.jp/contests/ABC056?lang=ja'

[tasks]
[tasks.a]
id = 'abc056_a'
path = '/home/kshino/workspace/compe_prog_new/ABC056/a/main.py'

[tasks.b]
id = 'abc056_b'
path = '/home/kshino/workspace/compe_prog_new/ABC056/b/main.py'

[tasks.c]
id = 'arc070_a'
path = '/home/kshino/workspace/compe_prog_new/ABC056/c/main.py'

[tasks.d]
id = 'arc070_b'
path = '/home/kshino/workspace/compe_prog_new/ABC056/d/main.py'


