[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc203'
url = 'https://atcoder.jp/contests/abc203?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC203/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC203/b/main.py'

[tasks.c]
id = 'abc203_c'
path = '/home/kshino/workspace/compe_prog_new/ABC203/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC203/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC203/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC203/f/main.py'
