[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC090'
url = 'https://atcoder.jp/contests/ABC090?lang=ja'

[tasks]
[tasks.a]
id = 'abc090_a'
path = '/home/kshino/workspace/compe_prog_new/ABC090/a/main.py'

[tasks.b]
id = 'abc090_b'
path = '/home/kshino/workspace/compe_prog_new/ABC090/b/main.py'

[tasks.c]
id = 'arc091_a'
path = '/home/kshino/workspace/compe_prog_new/ABC090/c/main.py'

[tasks.d]
id = 'arc091_b'
path = '/home/kshino/workspace/compe_prog_new/ABC090/d/main.py'


