[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC182'
url = 'https://atcoder.jp/contests/ABC182?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC182/a/main.py'

[tasks.b]
id = 'abc182_b'
path = '/home/kshino/workspace/compe_prog_new/ABC182/b/main.py'

[tasks.c]
id = 'abc182_c'
path = '/home/kshino/workspace/compe_prog_new/ABC182/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC182/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC182/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC182/f/main.py'
