[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC306'
url = 'https://atcoder.jp/contests/ABC306?lang=ja'

[tasks]
[tasks.a]
id = 'abc306_a'
path = '/home/kshino/workspace/compe_prog_new/ABC306/a/main.py'

[tasks.b]
id = 'abc306_b'
path = '/home/kshino/workspace/compe_prog_new/ABC306/b/main.py'

[tasks.c]
id = 'abc306_c'
path = '/home/kshino/workspace/compe_prog_new/ABC306/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC306/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC306/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC306/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC306/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC306/g/main.py'


