[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC001'
url = 'https://atcoder.jp/contests/ABC001?lang=ja'

[tasks]
[tasks.a]
id = 'abc001_1'
path = '/home/kshino/workspace/compe_prog_new/ABC001/a/main.py'

[tasks.b]
id = 'abc001_2'
path = '/home/kshino/workspace/compe_prog_new/ABC001/b/main.py'

[tasks.c]
id = 'abc001_3'
path = '/home/kshino/workspace/compe_prog_new/ABC001/c/main.py'

[tasks.d]
id = 'abc001_4'
path = '/home/kshino/workspace/compe_prog_new/ABC001/d/main.py'


