[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc344'
url = 'https://atcoder.jp/contests/abc344?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc344/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc344/b/main.py'

[tasks.c]
id = 'abc344_c'
path = '/home/kshino/workspace/compe_prog_new/abc344/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc344/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc344/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc344/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc344/g/main.py'
