[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc242'
url = 'https://atcoder.jp/contests/abc242?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC242/g/main.py'
