[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc339'
url = 'https://atcoder.jp/contests/abc339?lang=ja'

[tasks]
[tasks.a]
id = 'abc339_a'
path = '/home/kshino/workspace/compe_prog_new/abc339/a/main.py'

[tasks.b]
id = 'abc339_b'
path = '/home/kshino/workspace/compe_prog_new/abc339/b/main.py'

[tasks.c]
id = 'abc339_c'
path = '/home/kshino/workspace/compe_prog_new/abc339/c/main.py'

[tasks.d]
id = 'abc339_d'
path = '/home/kshino/workspace/compe_prog_new/abc339/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc339/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc339/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc339/g/main.py'
