[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC071'
url = 'https://atcoder.jp/contests/ABC071?lang=ja'

[tasks]
[tasks.a]
id = 'abc071_a'
path = '/home/kshino/workspace/compe_prog_new/ABC071/a/main.py'

[tasks.b]
id = 'abc071_b'
path = '/home/kshino/workspace/compe_prog_new/ABC071/b/main.py'

[tasks.c]
id = 'arc081_a'
path = '/home/kshino/workspace/compe_prog_new/ABC071/c/main.py'

[tasks.d]
id = 'arc081_b'
path = '/home/kshino/workspace/compe_prog_new/ABC071/d/main.py'


