[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ARC161'
url = 'https://atcoder.jp/contests/ARC161?lang=ja'

[tasks]
[tasks.a]
id = 'arc161_a'
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC161/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC161/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC161/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC161/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC161/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ARC/ARC161/f/main.py'


