[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC202'
url = 'https://atcoder.jp/contests/ABC202?lang=ja'

[tasks]
[tasks.a]
id = 'abc202_a'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230524night/ABC202/a/main.py'

[tasks.b]
id = 'abc202_b'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230524night/ABC202/b/main.py'

[tasks.c]
id = 'abc202_c'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230524night/ABC202/c/main.py'

[tasks.d]
id = 'abc202_d'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230524night/ABC202/d/main.py'

[tasks.e]
id = 'abc202_e'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230524night/ABC202/e/main.py'

[tasks.f]
id = 'abc202_f'
path = '/home/kshino/workspace/compe_prog_new/VirtualContest/nanika20230524night/ABC202/f/main.py'


