[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'agc019'
url = 'https://atcoder.jp/contests/agc019?lang=ja'

[tasks]
[tasks.a]
id = 'agc019_a'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC019/a/main.py'

[tasks.b]
id = 'agc019_b'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC019/b/main.py'

[tasks.c]
id = 'agc019_c'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC019/c/main.py'

[tasks.d]
id = 'agc019_d'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC019/d/main.py'

[tasks.e]
id = 'agc019_e'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC019/e/main.py'

[tasks.f]
id = 'agc019_f'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC019/f/main.py'
