[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC088'
url = 'https://atcoder.jp/contests/ABC088?lang=ja'

[tasks]
[tasks.a]
id = 'abc088_a'
path = '/home/kshino/workspace/compe_prog_new/ABC088/a/main.py'

[tasks.b]
id = 'abc088_b'
path = '/home/kshino/workspace/compe_prog_new/ABC088/b/main.py'

[tasks.c]
id = 'abc088_c'
path = '/home/kshino/workspace/compe_prog_new/ABC088/c/main.py'

[tasks.d]
id = 'abc088_d'
path = '/home/kshino/workspace/compe_prog_new/ABC088/d/main.py'


