[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC027'
url = 'https://atcoder.jp/contests/ABC027?lang=ja'

[tasks]
[tasks.a]
id = 'abc027_a'
path = '/home/kshino/workspace/compe_prog_new/ABC027/a/main.py'

[tasks.b]
id = 'abc027_b'
path = '/home/kshino/workspace/compe_prog_new/ABC027/b/main.py'

[tasks.c]
id = 'abc027_c'
path = '/home/kshino/workspace/compe_prog_new/ABC027/c/main.py'

[tasks.d]
id = 'abc027_d'
path = '/home/kshino/workspace/compe_prog_new/ABC027/d/main.py'


