[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC100'
url = 'https://atcoder.jp/contests/ABC100?lang=ja'

[tasks]
[tasks.a]
id = 'abc100_a'
path = '/home/kshino/workspace/compe_prog_new/ABC100/a/main.py'

[tasks.b]
id = 'abc100_b'
path = '/home/kshino/workspace/compe_prog_new/ABC100/b/main.py'

[tasks.c]
id = 'abc100_c'
path = '/home/kshino/workspace/compe_prog_new/ABC100/c/main.py'

[tasks.d]
id = 'abc100_d'
path = '/home/kshino/workspace/compe_prog_new/ABC100/d/main.py'


