[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc340'
url = 'https://atcoder.jp/contests/abc340?lang=ja'

[tasks]
[tasks.a]
id = 'abc340_a'
path = '/home/kshino/workspace/compe_prog_new/abc340/a/main.py'

[tasks.b]
id = 'abc340_b'
path = '/home/kshino/workspace/compe_prog_new/abc340/b/main.py'

[tasks.c]
id = 'abc340_c'
path = '/home/kshino/workspace/compe_prog_new/abc340/c/main.py'

[tasks.d]
id = 'abc340_d'
path = '/home/kshino/workspace/compe_prog_new/abc340/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc340/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc340/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc340/g/main.py'
