[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC096'
url = 'https://atcoder.jp/contests/ABC096?lang=ja'

[tasks]
[tasks.a]
id = 'abc096_a'
path = '/home/kshino/workspace/compe_prog_new/ABC096/a/main.py'

[tasks.b]
id = 'abc096_b'
path = '/home/kshino/workspace/compe_prog_new/ABC096/b/main.py'

[tasks.c]
id = 'abc096_c'
path = '/home/kshino/workspace/compe_prog_new/ABC096/c/main.py'

[tasks.d]
id = 'abc096_d'
path = '/home/kshino/workspace/compe_prog_new/ABC096/d/main.py'


