[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC116'
url = 'https://atcoder.jp/contests/ABC116?lang=ja'

[tasks]
[tasks.a]
id = 'abc116_a'
path = '/home/kshino/workspace/compe_prog_new/ABC116/a/main.py'

[tasks.b]
id = 'abc116_b'
path = '/home/kshino/workspace/compe_prog_new/ABC116/b/main.py'

[tasks.c]
id = 'abc116_c'
path = '/home/kshino/workspace/compe_prog_new/ABC116/c/main.py'

[tasks.d]
id = 'abc116_d'
path = '/home/kshino/workspace/compe_prog_new/ABC116/d/main.py'


