[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'agc024'
url = 'https://atcoder.jp/contests/agc024?lang=ja'

[tasks]
[tasks.a]
id = 'agc024_a'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC024/a/main.py'

[tasks.b]
id = 'agc024_b'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC024/b/main.py'

[tasks.c]
id = 'agc024_c'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC024/c/main.py'

[tasks.d]
id = 'agc024_d'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC024/d/main.py'

[tasks.e]
id = 'agc024_e'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC024/e/main.py'

[tasks.f]
id = 'agc024_f'
path = '/home/kshino/workspace/compe_prog_new/AGC/AGC024/f/main.py'
