[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC300'
url = 'https://atcoder.jp/contests/ABC300?lang=ja'

[tasks]
[tasks.a]
id = 'abc300_a'
path = '/home/kshino/workspace/compe_prog_new/ABC300/a/main.py'

[tasks.b]
id = 'abc300_b'
path = '/home/kshino/workspace/compe_prog_new/ABC300/b/main.py'

[tasks.c]
id = 'abc300_c'
path = '/home/kshino/workspace/compe_prog_new/ABC300/c/main.py'

[tasks.d]
id = 'abc300_d'
path = '/home/kshino/workspace/compe_prog_new/ABC300/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC300/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC300/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC300/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC300/g/main.py'


