[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC115'
url = 'https://atcoder.jp/contests/ABC115?lang=ja'

[tasks]
[tasks.a]
id = 'abc115_a'
path = '/home/kshino/workspace/compe_prog_new/ABC115/a/main.py'

[tasks.b]
id = 'abc115_b'
path = '/home/kshino/workspace/compe_prog_new/ABC115/b/main.py'

[tasks.c]
id = 'abc115_c'
path = '/home/kshino/workspace/compe_prog_new/ABC115/c/main.py'

[tasks.d]
id = 'abc115_d'
path = '/home/kshino/workspace/compe_prog_new/ABC115/d/main.py'


