[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc137'
url = 'https://atcoder.jp/contests/abc137?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC137/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC137/b/main.py'

[tasks.c]
id = 'abc137_c'
path = '/home/kshino/workspace/compe_prog_new/ABC137/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC137/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC137/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC137/f/main.py'
