[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'hitachi2020'
url = 'https://atcoder.jp/contests/hitachi2020?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/hitachi2020/a/main.py'

[tasks.b]
id = 'hitachi2020_b'
path = '/home/kshino/workspace/compe_prog_new/other/hitachi2020/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/hitachi2020/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/hitachi2020/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/hitachi2020/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/hitachi2020/f/main.py'
