[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC101'
url = 'https://atcoder.jp/contests/ABC101?lang=ja'

[tasks]
[tasks.a]
id = 'abc101_a'
path = '/home/kshino/workspace/compe_prog_new/ABC101/a/main.py'

[tasks.b]
id = 'abc101_b'
path = '/home/kshino/workspace/compe_prog_new/ABC101/b/main.py'

[tasks.c]
id = 'arc099_a'
path = '/home/kshino/workspace/compe_prog_new/ABC101/c/main.py'

[tasks.d]
id = 'arc099_b'
path = '/home/kshino/workspace/compe_prog_new/ABC101/d/main.py'


