[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC301'
url = 'https://atcoder.jp/contests/ABC301?lang=ja'

[tasks]
[tasks.a]
id = 'abc301_a'
path = '/home/kshino/workspace/compe_prog_new/ABC301/a/main.py'

[tasks.b]
id = 'abc301_b'
path = '/home/kshino/workspace/compe_prog_new/ABC301/b/main.py'

[tasks.c]
id = 'abc301_c'
path = '/home/kshino/workspace/compe_prog_new/ABC301/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC301/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC301/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC301/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC301/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC301/g/main.py'


