[config]
buildcmd = ''
filename = 'main.py'
lang = '4006'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC247'
url = 'https://atcoder.jp/contests/ABC247?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC247/a/main.py'

[tasks.b]
id = 'abc247_b'
path = '/home/kshino/workspace/compe_prog_new/ABC247/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC247/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC247/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC247/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC247/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC247/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC247/g/main.py'


