[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC098'
url = 'https://atcoder.jp/contests/ABC098?lang=ja'

[tasks]
[tasks.a]
id = 'abc098_a'
path = '/home/kshino/workspace/compe_prog_new/ABC098/a/main.py'

[tasks.b]
id = 'abc098_b'
path = '/home/kshino/workspace/compe_prog_new/ABC098/b/main.py'

[tasks.c]
id = 'arc098_a'
path = '/home/kshino/workspace/compe_prog_new/ABC098/c/main.py'

[tasks.d]
id = 'arc098_b'
path = '/home/kshino/workspace/compe_prog_new/ABC098/d/main.py'


