[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC010'
url = 'https://atcoder.jp/contests/ABC010?lang=ja'

[tasks]
[tasks.a]
id = 'abc010_1'
path = '/home/kshino/workspace/compe_prog_new/ABC010/a/main.py'

[tasks.b]
id = 'abc010_2'
path = '/home/kshino/workspace/compe_prog_new/ABC010/b/main.py'

[tasks.c]
id = 'abc010_3'
path = '/home/kshino/workspace/compe_prog_new/ABC010/c/main.py'

[tasks.d]
id = 'abc010_4'
path = '/home/kshino/workspace/compe_prog_new/ABC010/d/main.py'


