[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc329'
url = 'https://atcoder.jp/contests/abc329?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc329/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc329/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc329/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc329/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc329/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc329/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/abc329/g/main.py'
