[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC002'
url = 'https://atcoder.jp/contests/ABC002?lang=ja'

[tasks]
[tasks.a]
id = 'abc002_1'
path = '/home/kshino/workspace/compe_prog_new/ABC002/a/main.py'

[tasks.b]
id = 'abc002_2'
path = '/home/kshino/workspace/compe_prog_new/ABC002/b/main.py'

[tasks.c]
id = 'abc002_3'
path = '/home/kshino/workspace/compe_prog_new/ABC002/c/main.py'

[tasks.d]
id = 'abc002_4'
path = '/home/kshino/workspace/compe_prog_new/ABC002/d/main.py'


