[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'panasonic2020'
url = 'https://atcoder.jp/contests/panasonic2020?lang=ja'

[tasks]
[tasks.a]
id = 'panasonic2020_a'
path = '/home/kshino/workspace/compe_prog_new/other/panasonic2020/a/main.py'

[tasks.b]
id = 'panasonic2020_b'
path = '/home/kshino/workspace/compe_prog_new/other/panasonic2020/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/panasonic2020/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/panasonic2020/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/panasonic2020/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/other/panasonic2020/f/main.py'


