[config]
buildcmd = ''
filename = 'main.py'
lang = '4047'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'ABC273'
url = 'https://atcoder.jp/contests/ABC273?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC273/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC273/b/main.py'

[tasks.c]
id = 'abc273_c'
path = '/home/kshino/workspace/compe_prog_new/ABC273/c/main.py'

[tasks.d]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC273/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC273/e/main.py'

[tasks.ex]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC273/ex/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC273/f/main.py'

[tasks.g]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC273/g/main.py'


