[config]
buildcmd = ''
filename = 'main.py'
lang = '5078'
runcmd = 'python3 {{ .file }}'

[contest]
name = 'abc174'
url = 'https://atcoder.jp/contests/abc174?lang=ja'

[tasks]
[tasks.a]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC174/a/main.py'

[tasks.b]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC174/b/main.py'

[tasks.c]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC174/c/main.py'

[tasks.d]
id = 'abc174_d'
path = '/home/kshino/workspace/compe_prog_new/ABC174/d/main.py'

[tasks.e]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC174/e/main.py'

[tasks.f]
id = ''
path = '/home/kshino/workspace/compe_prog_new/ABC174/f/main.py'
